import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

/// 分类 / 标签 / 来源可选图标。`key` 与 DB `icon` 字段对应。
///
/// 这一份是 Icon Picker 展示给用户的白名单，按字母序排列。
const Map<String, IconData> kIconRegistry = <String, IconData>{
  'activity': LucideIcons.activity,
  'apple': LucideIcons.apple,
  'baby': LucideIcons.baby,
  'banknote': LucideIcons.banknote,
  'bath': LucideIcons.bath,
  'bed': LucideIcons.bed,
  'beer': LucideIcons.beer,
  'bike': LucideIcons.bike,
  'book': LucideIcons.book,
  'book-open': LucideIcons.bookOpen,
  'briefcase': LucideIcons.briefcase,
  'briefcase-medical': LucideIcons.briefcaseMedical,
  'building': LucideIcons.building,
  'bus': LucideIcons.bus,
  'cake': LucideIcons.cake,
  'car': LucideIcons.car,
  'cat': LucideIcons.cat,
  'circle-dollar-sign': LucideIcons.circleDollarSign,
  'clapperboard': LucideIcons.clapperboard,
  'coffee': LucideIcons.coffee,
  'coins': LucideIcons.coins,
  'computer': LucideIcons.computer,
  'cookie': LucideIcons.cookie,
  'credit-card': LucideIcons.creditCard,
  'cross': LucideIcons.cross,
  'dog': LucideIcons.dog,
  'dollar-sign': LucideIcons.dollarSign,
  'droplet': LucideIcons.droplet,
  'dumbbell': LucideIcons.dumbbell,
  'euro': LucideIcons.euro,
  'file-text': LucideIcons.fileText,
  'film': LucideIcons.film,
  'fish': LucideIcons.fish,
  'flame': LucideIcons.flame,
  'footprints': LucideIcons.footprints,
  'fuel': LucideIcons.fuel,
  'gamepad2': LucideIcons.gamepad2,
  'gem': LucideIcons.gem,
  'gift': LucideIcons.gift,
  'globe': LucideIcons.globe,
  'graduation-cap': LucideIcons.graduationCap,
  'hamburger': LucideIcons.hamburger,
  'hammer': LucideIcons.hammer,
  'hand-coins': LucideIcons.handCoins,
  'headphones': LucideIcons.headphones,
  'heart-pulse': LucideIcons.heartPulse,
  'home': LucideIcons.home,
  'hospital': LucideIcons.hospital,
  'house': LucideIcons.house,
  'ice-cream': LucideIcons.iceCream,
  'japanese-yen': LucideIcons.japaneseYen,
  'joystick': LucideIcons.joystick,
  'landmark': LucideIcons.landmark,
  'laptop': LucideIcons.laptop,
  'map': LucideIcons.map,
  'monitor': LucideIcons.monitor,
  'mountain': LucideIcons.mountain,
  'music': LucideIcons.music,
  'notebook': LucideIcons.notebook,
  'package': LucideIcons.package,
  'package-check': LucideIcons.packageCheck,
  'paintbrush': LucideIcons.paintbrush,
  'palette': LucideIcons.palette,
  'party-popper': LucideIcons.partyPopper,
  'paw-print': LucideIcons.pawPrint,
  'pencil': LucideIcons.pencil,
  'percent': LucideIcons.percent,
  'phone': LucideIcons.phone,
  'piggy-bank': LucideIcons.piggyBank,
  'pill': LucideIcons.pill,
  'pizza': LucideIcons.pizza,
  'plane': LucideIcons.plane,
  'plug': LucideIcons.plug,
  'pound-sterling': LucideIcons.poundSterling,
  'receipt': LucideIcons.receipt,
  'receipt-text': LucideIcons.receiptText,
  'sandwich': LucideIcons.sandwich,
  'scissors': LucideIcons.scissors,
  'shield': LucideIcons.shield,
  'shield-check': LucideIcons.shieldCheck,
  'ship': LucideIcons.ship,
  'shirt': LucideIcons.shirt,
  'shopping-bag': LucideIcons.shoppingBag,
  'shopping-basket': LucideIcons.shoppingBasket,
  'shopping-cart': LucideIcons.shoppingCart,
  'sofa': LucideIcons.sofa,
  'stethoscope': LucideIcons.stethoscope,
  'tag': LucideIcons.tag,
  'tent': LucideIcons.tent,
  'ticket': LucideIcons.ticket,
  'train-front': LucideIcons.trainFront,
  'trending-up': LucideIcons.trendingUp,
  'trophy': LucideIcons.trophy,
  'truck': LucideIcons.truck,
  'tv': LucideIcons.tv,
  'user': LucideIcons.user,
  'user-round': LucideIcons.userRound,
  'utensils': LucideIcons.utensils,
  'volleyball': LucideIcons.volleyball,
  'wallet': LucideIcons.wallet,
  'wifi': LucideIcons.wifi,
  'wine': LucideIcons.wine,
  'wrench': LucideIcons.wrench,
  'zap': LucideIcons.zap,
};

/// 旧版 DB 行可能仍持有这些 key（不再展示给用户挑选，但仍能正确渲染）。
const Map<String, IconData> _kLegacyIconRegistry = <String, IconData>{
  'box': LucideIcons.box,
  'circle-plus': LucideIcons.plusCircle,
  'smartphone': LucideIcons.smartphone,
  'gamepad': LucideIcons.gamepad2,
  'paw': LucideIcons.pawPrint,
  'leaf': LucideIcons.leaf,
  'star': LucideIcons.star,
  'hash': LucideIcons.hash,
};

/// 渲染 [icon] 对应的 [IconData]；找不到时落回 [LucideIcons.tag]。
IconData iconFor(String? key) {
  if (key == null) return LucideIcons.tag;
  return kIconRegistry[key] ?? _kLegacyIconRegistry[key] ?? LucideIcons.tag;
}

/// 推荐配色（与 DESIGN_STANDARDS 调色板对齐）。
/// 排成 10 列网格；29 色 + 末尾一个自定义 `+` 槽，刚好 3 行。
const List<String> kPaletteHex = <String>[
  // row 1: 绿—青系
  '#10b981', '#34d399', '#059669', '#84cc16', '#22c55e',
  '#14b8a6', '#06b6d4', '#0ea5e9', '#0284c7', '#0d9488',
  // row 2: 蓝—紫—粉
  '#3b82f6', '#6366f1', '#4f46e5', '#8b5cf6', '#a855f7',
  '#d946ef', '#ec4899', '#db2777', '#f43f5e', '#e11d48',
  // row 3: 红—橙—黄—灰（末尾留给自定义 + 按钮）
  '#ef4444', '#dc2626', '#f97316', '#ea580c', '#f59e0b',
  '#facc15', '#eab308', '#64748b', '#475569',
];
